### ISSUE TITLE
Incomplete Credentials Provided

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#247]
From Slack:

I just tried installing twarc on a new computer, however, i keep getting an error.

‘’’
Traceback (most recent call last):
  File "/home/kiiki/.local/bin/twarc", line 11, in <module>
    sys.exit(main())
  File "/home/kiiki/.local/lib/python3.6/site-packages/twarc/command.py", line 90, in main
    protected=args.protected
  File "/home/kiiki/.local/lib/python3.6/site-packages/twarc/client.py", line 69, in __init__
    self.validate_keys()
  File "/home/kiiki/.local/lib/python3.6/site-packages/twarc/client.py", line 762, in validate_keys
    raise RuntimeError('Incomplete credentials provided.')
RuntimeError: Incomplete credentials provided."
‘’’

**Comment by SamHames** [comment]
This one's on me - I think it should only affect new installs of 1.6.0. 

The problem is key validation is on by default in the client, which means that initialisition of the client is always going to fail before configuration is run.

I'm submitting a PR which makes sure it doesn't try to validate keys for the configure command, and I'll add an option to disable key checking.
