### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by mthielk** [DocNow/twarc#318]
I just wanted to share the stacktrace for an error I've been getting.

It seems like just catching requests.exceptions.ChunkedEncodingError in catch_conn_reset would be a good idea.
```
hydrating 2020-03/coronavirus-tweet-id-2020-03-16-04.txt
rate limit exceeded: sleeping 540.7469525337219 secs
caught connection error ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) on 1 try
hydrating 2020-03/coronavirus-tweet-id-2020-03-16-05.txt
hydrating 2020-03/coronavirus-tweet-id-2020-03-16-06.txt
rate limit exceeded: sleeping 540.9134702682495 secs
hydrating 2020-03/coronavirus-tweet-id-2020-03-16-07.txt
Traceback (most recent call last):
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/urllib3/response.py", line 362, in _error_catcher
    yield
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/urllib3/response.py", line 444, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/urllib3/response.py", line 496, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/urllib3/response.py", line 461, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/urllib3/response.py", line 380, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrate.py", line 42, in <module>
    main()
  File "hydrate.py", line 25, in main
    hydrate(path)
  File "hydrate.py", line 37, in hydrate
    for tweet in twarc.hydrate(id_file.open()):
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/twarc/client.py", line 486, in hydrate
    "include_ext_alt_text": 'true'
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/twarc/decorators.py", line 17, in new_f
    resp = f(*args, **kwargs)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/twarc/decorators.py", line 77, in new_f
    return f(self, *args, **kwargs)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/twarc/decorators.py", line 87, in new_f
    return f(self, *args, **kwargs)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/twarc/decorators.py", line 103, in new_f
    return f(self, *args, **kwargs)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/twarc/client.py", line 729, in post
    **kwargs)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/homes/thielk/envs/misc/lib/python3.6/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by edsu** [comment]
Thanks! What version of Python are you using?

**Comment by mthielk** [comment]
python 3.6.8

**Comment by edsu** [comment]
Could you verify if you have pyOpenSSL installed?

```python
import OpenSSL
```

**Comment by mthielk** [comment]
I do not

**Comment by edsu** [comment]
I just released v1.8.1 to pypi for you to try.

**Comment by mthielk** [comment]
Alright, I pulled it down and I'm running it now. It only happened every couple days though so I'll let you know if it happens again but it was pretty rare. Thanks for such a speedy response!

**Comment by numeroteca** [comment]
I got a similar error message. Until now I was running twarc2 without problems.

I run:
`twarc2 search 'barcenas' --start-time 2013-04-12 --end-time 2013-05-13 --archive --flatten > 130412-130512.jsonl`

And I got: 
```
Traceback (most recent call last):
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/http/client.py", line 454, in read
    n = self.readinto(b)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/http/client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/numeroteca/.pyenv/versions/3.8.1/bin/twarc2", line 11, in <module>
    load_entry_point('twarc==2.0.8', 'console_scripts', 'twarc2')()
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/decorators.py", line 176, in __call__
    return self.f(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/command2.py", line 184, in search
    for result in search_method(query, since_id, until_id, start_time, end_time):
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/client2.py", line 126, in _search
    for response in self.get_paginated(url, params=params):
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/client2.py", line 658, in get_paginated
    resp = self.get(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/decorators.py", line 31, in new_f
    resp = f(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/decorators.py", line 100, in new_f
    return f(self, *args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/decorators.py", line 111, in new_f
    return f(self, *args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/decorators.py", line 127, in new_f
    return f(self, *args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc/client2.py", line 592, in get
    r = self.last_response = self.client.get(
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

Then I run a smilar, but with shorter period of time, and it gave no problem:
`twarc2 search 'barcenas' --start-time 2013-04-12 --end-time 2013-04-20 --archive --flatten > 130412-130419.jsonl`

Is there a limit in the period of requested tweets?

**Comment by edsu** [comment]
There should be no limit, but I think what is happening is that an intermittent network error is causing twarc to stop prematurely. I think the longer the time frame the longer that twarc needs to run and therefore the more likely a network error becomes. Am I correct in saying that there is *some* data in the 130412-130512.jsonl  file?

**Comment by edsu** [comment]
@numeroteca I think you will want to follow issue #471 since that applies to twarc2.

**Comment by numeroteca** [comment]
Yes, 130412-130512.jsonl had some data in it. I'll follow #471 then.
Thanks.
