### ISSUE TITLE
requests.exceptions.HTTPError: 422 Client Error:

### ISSUE THREAD

**Issue by csantanaes** [DocNow/twarc#371]
I tried to run command to retrieve data Search Tweets: Full ArchiveSandbox twarc --app_auth search blacklivesmatter --fullarchive DevFullArchive> 30tweets.jsonl and the error is shown below. Can someone help me?

C:\dados\TWITTER\earte>twarc --app_auth search blacklivesmatter --fullarchive DevFullArchive > 30tweets.jsonl
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\twarc.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\twarc\command.py", line 284, in main
    for thing in things:
  File "c:\programdata\miniconda3\lib\site-packages\twarc\client.py", line 208, in premium_search
    resp = self.get(url, params=params)
  File "c:\programdata\miniconda3\lib\site-packages\twarc\decorators.py", line 60, in new_f
    resp.raise_for_status()
  File "c:\programdata\miniconda3\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.twitter.com/1.1/tweets/search/fullarchive/DevFullArchive.json?query=blacklivesmatter&maxResults=500

**Comment by edsu** [comment]
Hi @csantanaes,

This is kind of buried in the [documentation](https://github.com/DocNow/twarc#premium-search-api):

> If your environment is sandboxed you will need to use --sandbox so that twarc knows not to request more than 100 tweets at a time (the default for non-sandboxed environments is 500)

Can you try your command above with the `--sandbox` argument?
