### ISSUE TITLE
twarc not currently installable

### ISSUE THREAD

**Issue by dtrodrigues** [DocNow/twarc#425]
When getting the version information in setup.py, it tries to import `requests` before `install_requires` installs it:

```
# python3 -m pip install twarc==2.0.0
Collecting twarc==2.0.0
  Using cached twarc-2.0.0.tar.gz (42 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ngsx4g1/twarc_a54374d52ef34d0e8b5894d5ca06dc13/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ngsx4g1/twarc_a54374d52ef34d0e8b5894d5ca06dc13/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-31wd15ee
         cwd: /tmp/pip-install-0ngsx4g1/twarc_a54374d52ef34d0e8b5894d5ca06dc13/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0ngsx4g1/twarc_a54374d52ef34d0e8b5894d5ca06dc13/setup.py", line 4, in <module>
        from twarc.version import version
      File "/tmp/pip-install-0ngsx4g1/twarc_a54374d52ef34d0e8b5894d5ca06dc13/twarc/__init__.py", line 2, in <module>
        from .client import Twarc
      File "/tmp/pip-install-0ngsx4g1/twarc_a54374d52ef34d0e8b5894d5ca06dc13/twarc/client.py", line 10, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
```
or from head of current master (https://github.com/DocNow/twarc/commit/ba054d9923e4c5471762405195a5cd279521d464)
```
# python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from twarc.version import version
  File "/root/twarc/twarc/__init__.py", line 2, in <module>
    from .client import Twarc
  File "/root/twarc/twarc/client.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by igorbrigadir** [comment]
Thanks! This is indeed a bug. Gonna fix it now but a quick workaround would be to run:

```
git clone https://github.com/DocNow/twarc.git
cd twarc
git submodule update --init
pip install .
```

**Comment by edsu** [comment]
Thanks, a fix should be available momentarily.

**Comment by edsu** [comment]
@dtrodrigues can you give `pip install --upgrade twarc` another try and let us know if it works this time?

**Comment by edsu** [comment]
Well, it looks good for me so I'm going to close this. Please feel free to reopen if you continue to encounter trouble @dtrodrigues

**Comment by dtrodrigues** [comment]
Thanks for the quick fix.
