### ISSUE TITLE
friends and followers to collect

### ISSUE THREAD

**Issue by DV777** [DocNow/twarc#474]
Hello, I am trying to use Twarc to get a list of friends and a list of followers from a list of ids I obtained from a specific group of handles.

However I keep on getting this kind of error messages. I don't get where it comes from. I set Twarc according to the wiki, configuration went without any issue.

How to solve this ? 

Thanks in advance for the help and time !

```C:\Twarc>twarc followers friendListToCollect_ids.txt > follower_ids.txt
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\client.py", line 359, in follower_ids
    resp = self.get(url, params=params, allow_404=True)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\decorators.py", line 73, in new_f
    resp.raise_for_status()
  File "C:\ProgramData\Anaconda3\Lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.twitter.com/1.1/followers/ids.json?screen_name=friendListToCollect_ids.txt&cursor=-1&tweet_mode=extended
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\twarc.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\command.py", line 284, in main
    for thing in things:
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\client.py", line 363, in follower_ids
    log.info("no users matching %s", screen_name)
NameError: name 'screen_name' is not defined

C:\Twarc>twarc friends friendListToCollect_ids.txt > friend_ids.txt
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\twarc.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\command.py", line 284, in main
    for thing in things:
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\client.py", line 397, in friend_ids
    raise e
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\client.py", line 392, in friend_ids
    resp = self.get(url, params=params, allow_404=True)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\twarc\decorators.py", line 73, in new_f
    resp.raise_for_status()
  File "C:\ProgramData\Anaconda3\Lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.twitter.com/1.1/friends/ids.json?screen_name=friendListToCollect_ids.txt&cursor=-1&tweet_mode=extended

**Comment by igorbrigadir** [comment]
You definitely want to use v1.1 API right? in that case: https://twarc-project.readthedocs.io/en/latest/#friends

> collect the friend user ids for exactly one user screen name per request

The command accepts only 1 user name, not a text file.

If you're trying to use v2, it's https://twarc-project.readthedocs.io/en/latest/twarc2/#following and it's also 1 user name not a text file.

This post for v2 API may also help https://twittercommunity.com/t/downloading-friends-from-a-list-of-users/155024/4?u=igorbrigadir

**Comment by DV777** [comment]
Thanks ! I thought it could handle a list.
