### ISSUE TITLE
Is it possible to unshorten urls with twarc2?

### ISSUE THREAD

**Issue by numeroteca** [DocNow/twarc#538]
I've gathered tweets with twarc2.
I want to unshorten their URL. 
Do I have to use twarc or is it possible to do it with twarc2?

I am looking in the documentation (https://twarc-project.readthedocs.io/en/latest/) and when running it with twarc, from the directory where I have this repository cloned and updated:

`cat archive_flatten.jsonl | utils/unshrtn.py > archive_flatten_unshrtn.jsonl`

 I get:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "utils/unshrtn.py", line 78, in rewrite_line
    for url_dict in tweet["entities"]["urls"]:
KeyError: 'urls'
"""

```

**Comment by edsu** [comment]
Ah yes, that would need to be updated to work with the new v2 flavor of JSON. If you are in a pinch and need it quickly I think I can quickly update it. But really it should be made into a plugin.

**Comment by edsu** [comment]
I've updated unshrtn.py to hopefully work with both v1 and v2 data for now. Can you give it a try?

**Comment by numeroteca** [comment]
It is working, but it goes very slow for a list of tweets over thousands. I am not sure where I have to look to see if it has worked. I run:

`cat file.jsonl | utils/unshrtn.py > file.jsonl`

However, while trying to verify that it had worked with a portion of the file, I found that the original list of tweets had already the `entities.url` variable that has in it the `expanded_url` variable!! 

Examples:
`[{"start": 100, "end": 123, "url": "https://t.co/Bteg71vVxn", "expanded_url": "https://twitter.com/Mgm171171/status/1435530037642637316/photo/1", "display_url": "pic.twitter.com/Bteg71vVxn"}]`

`[{"start": 83, "end": 106, "url": "https://t.co/Y0wezgjdl0", "expanded_url": "https://www.elconfidencial.com/espana/madrid/2021-09-07/universidad-periodismo-complutense-profesores_3218500/", "display_url": "elconfidencial.com/espana/madrid/\\u2026",  ... ] `

Is that right?

I see in the unshortened tweets by twarc that there is `unwound_url`: is it the same information as "expanded_url" or twarc2 is expanding other information?

**Comment by SamHames** [comment]
The expanded_url is what the user entered into the tweet - but that could
itself be a link shortener service like bit.ly. Unwinding is used to
resolve redirections and other things, especially for the case of link
shorteners - if you just need what the user entered then the expanded_url
is fine.

**Comment by numeroteca** [comment]
Oh, I understand now the difference between the exapand and the unwind. So I guess I'd need to apply the unshrten script for the non t.co links (that already expanded in `expanded_url`), so it will make the process much faster, so it does not have to go through all the links.
I'd need to create a filter in the command line to make select to select those tweets. I have to think how. 

I am trying first to rescue the original links introduced in the tweet with this R script, that uses the csv format:

```
data_twarc <- read.delim( pathto_flatten_file.csv , sep = ",") %>% mutate(
  time = as.POSIXct( substr( str_replace_all( created_at, "T"," "), 1,19 ), format="%Y-%m-%d %H:%M:%S", tz="UTC", start= as.Date("1970-01-01") )
) %>% select( time, everything()) %>% 
  # to expand url (unshortn)
  mutate(
    ent2 = entities.urls,
    test = strsplit(entities.urls, '": "'), 
    pre = test[[1]][3], 
    pre2 = strsplit(pre, '", "'), 
    url = pre2[[1]][1] ) %>% select( text, ent2, test, url, everything())
```

But something is not working. I might have to work directly with the json.

**Comment by edsu** [comment]
I don't think that twarc-csv uses the `unshortened_url` that is added by unshrtn.py since it is not a standard part of the JSON data. Are you expecting to see it in the CSV?

**Comment by numeroteca** [comment]
I want to count and classify tweets and users by the links they publish. As I am working in R with bidimensional structures (data.frame) I expect to have the URL in a variable that I can use: it could be in the transformed by twarc2 CSV or getting it in the script that I am creating in R in the data.frame.

**Comment by edsu** [comment]
I forgot that twarc-csv is serializing the JSON in the `entities.urls` column. So I guess `unshortened_url` is there? This new utility will unshorten anything labeled 'url' at any place in a tweet (which isn't pointed at twitter.com) so maybe that is slowing it down?

**Comment by numeroteca** [comment]
I see tweets that have `entities.urls` that have `unwound_url`.

For example this tweet "Y todo esto lo cuento algo mejor, con más detalle, en mi columna #DemocraciaPixelada, en @_infoLibre.\nGracias por la paciencia. Otra Universidad pública es posible. \nhttps://t.co/zzSQP9NE1D" has it:

`[{"start": 166, "end": 189, "url": "https://t.co/zzSQP9NE1D", "expanded_url": "https://www.infolibre.es/noticias/opinion/columnas/2021/09/08/la_verdad_sobre_caso_quiros_una_cronica_primera_persona_124235_1023.html", "display_url": "infolibre.es/noticias/opini\u2026", "images": [{"url": "https://pbs.twimg.com/news_img/1438049905516363779/NU2omRX-?format=jpg&name=orig", "width": 1200, "height": 675}, {"url": "https://pbs.twimg.com/news_img/1438049905516363779/NU2omRX-?format=jpg&name=150x150", "width": 150, "height": 150}], "status": 200, "title": "La verdad sobre el 'caso Quir\u00f3s': una cr\u00f3nica en primera persona", "description": "Acomp\u00e1\u00f1enme en esta ins\u00f3lita historia de presiones para retirarme de un concurso p\u00fablico, puntuaciones imposibles, entrevistas ama\u00f1adas, documentos robados, amenazas y prevaricaci\u00f3n. Prometo no aburrirles.", "unwound_url": "https://www.infolibre.es/noticias/opinion/columnas/2021/09/08/la_verdad_sobre_caso_quiros_una_cronica_primera_persona_124235_1023.html"}]`

but other tweets like this "Dedocracia: la sombra de las plazas 'con bicho' sobrevuela otra vez la Complutense https://t.co/u0Re0LwO5E?" don't have `unwound_url` in `entities.urls`:
`[{"start": 83, "end": 106, "url": "https://t.co/u0Re0LwO5E", "expanded_url": "https://www.elconfidencial.com/espana/madrid/2021-09-07/universidad-periodismo-complutense-profesores_3218500/", "display_url": "elconfidencial.com/espana/madrid/\u2026"}]`

or this other "¡Le habrían contado como experiencia docente sus clases en la escuela municipal de teatro, a la que van menores de edad! No hace falta pasar Selectividad ni EvAU, ni nada. NO es educación superior. Como bien explica su propia página web. 🤨👇 https://t.co/SWBPD7ox2R":

`[{"start": 241, "end": 264, "url": "https://t.co/SWBPD7ox2R", "expanded_url": "https://twitter.com/miguelenlared/status/1435501241837178885/photo/1", "display_url": "pic.twitter.com/SWBPD7ox2R"}]`

So I don't exactly get how it works: when the script creates `unwound_url` and when not. As for the examples provided `unwound_url` gives the same results as `expanded_url`, would it be different with a bit.ly type URL?

My goal here is to analyze the links in the tweets.

Yesterday it took very long to process the first 518 tweets and I stopped the process. From those, there are 98 with `entities.urls` and only 30 of them have `unwound_url`. It's worth mentioning that truncated RT (that in the original RT had an URL but it does not appear in the truncated text) have their `entities.urls` variable empty.

**Comment by edsu** [comment]
Yes, I was noticing `unwound_url` too. I think it's something from their Enterprise Service that I guess is part of v2? @igorbrigadir or @SamHames have you see it in the wild yet?

**Comment by numeroteca** [comment]
I've documented my URL analysis in this wiki page https://github.com/DocNow/twarc/wiki/Analyzing-links-in-tweets

**Comment by igorbrigadir** [comment]
Great! Once the new version of the twarc-csv is done it should work much better, and we can update that page and put it in the main docs as an example analysis.
