### ISSUE TITLE
How to concatenate transformations in twarc2: cat, flatten and convert to csv?

### ISSUE THREAD

**Issue by numeroteca** [DocNow/twarc#539]
I am working with a lot of tweet files (downloaded with twarc2: file_1.json, file-2.json... file_n.json) that I need to convert to csv to process them with R.
I need to:

1. bind 
2. flatten
3. convert to csv

To do this I was trying to make all in one command line so I don't need to create all the intermediary files.
Something like:

`cat file* | twarc2 flatten | twarc2 csv binds/total_flatten.jsonl`

but it is not working. 

`Error: Invalid value for '[INFILE]': Could not open file: total_flattened.csv: No such file or directory`

What am I missing in the concatenation?

**Comment by edsu** [comment]
The problem is that the csv plugin is expecting to read CSV data from `binds/total_flatten.jsonl`. You will probably want to write the CSV data to a new .csv file?

    cat file* | twarc2 flatten | twarc2 csv > binds/total.csv

twarc-csv actually will now flatten data during conversion if needed so you could simply by doing:

        cat file* | twarc2 csv > binds/total.csv

**Comment by numeroteca** [comment]
Thanks for the solution (ups, I typed in my first message the wrong output extension). I don't understand the difference between > and - but is working.

At the beginning it was throwing this error:

```
Traceback (most recent call last):
  File "/home/numeroteca/.pyenv/versions/3.8.1/bin/twarc2", line 11, in <module>
    load_entry_point('twarc==2.4.3', 'console_scripts', 'twarc2')()
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc_csv.py", line 458, in csv
    if os.stat(infile.name).st_size == 0:
FileNotFoundError: [Errno 2] No such file or directory: '<stdin>'

```
But once I updated twarc and twacr-csv (`pip install --upgrade twarc` 2.3.10 to 2.4.3  and `pip install --upgrade twarc-csv` 0.3.6 to 0.3.8) it is working :-).
