### ISSUE TITLE
400 client error bad request when running twarc from script

### ISSUE THREAD

**Issue by jakobvandyk** [DocNow/twarc#555]
Hi, I'm pretty new to programming but am working on an assignment where I develop a plugin for QGIS. I want to use twarc2 as a library to collect tweets which are geotagged and then import them into QGIS to plot them on a map as points. 

However, in developing the twarc code as a script and trying to run it from the mac terminal I keep getting a 400 client error bad request message. I have upgraded and configured twarc 2, and searching from the command line works fine. Experimenting with parameters hasn't helped either. I am thinking this might be an environmental problem, but not exactly sure how to resolve it. If anyone is able to help I would greatly appreciate it.

The script:
from twarc import Twarc2, expansions
import datetime
import json

# Replace your bearer token below
client = Twarc2(bearer_token="AAAAAAAAAAAAAAAAAAAAADo%2BTgEAAAAAp6R9C0pJlX6DPu3lIgZMUPa2VbI%3DMRDsXO231NjyMdVF6PLyWPsvnHUYFXSLZgOQGf1KSSiCwN3dvN")

def main():
    # Specify the start time in UTC for the time period you want Tweets from
    start_time = datetime.datetime(2021, 10, 12, 1, 1, 1, 1, datetime.timezone.utc)

    # Specify the end time in UTC for the time period you want Tweets from
    end_time = datetime.datetime(2021, 10, 13, 1, 1, 1, 1, datetime.timezone.utc)

    # This is where we specify our query as discussed in module 5
    query = "has:geo"

    # The search_recent method call the recent search endpoint to get Tweets based on the query, start and end times
    search_results = client.search_recent(query=query, start_time=start_time, end_time=end_time, max_results=1)

    # Twarc returns all Tweets for the criteria set above, so we page through the results
    for page in search_results:
        # The Twitter API v2 returns the Tweet information and the user, media etc.  separately
        # so we use expansions.flatten to get all the information in a single JSON
        result = expansions.flatten(page)
        for tweet in result:
            # Here we are printing the recent Tweet object JSON to the console
            print(json.dumps(tweet))

if __name__ == "__main__":
    main()

The Output:
Unexpected HTTP response: <Response [400]>
Traceback (most recent call last):
  File "/Users/Jen/Desktop/GEOM2159/GeoTweet-GEOM2157/Test tweet.py", line 33, in <module>
    main()
  File "/Users/Jen/Desktop/GEOM2159/GeoTweet-GEOM2157/Test tweet.py", line 23, in main
    for page in search_results:
  File "/Users/Jen/opt/miniconda3/lib/python3.9/site-packages/twarc/client2.py", line 136, in _search
    for response in self.get_paginated(url, params=params):
  File "/Users/Jen/opt/miniconda3/lib/python3.9/site-packages/twarc/client2.py", line 786, in get_paginated
    resp = self.get(*args, **kwargs)
  File "/Users/Jen/opt/miniconda3/lib/python3.9/site-packages/twarc/decorators2.py", line 111, in new_f
    raise e
  File "/Users/Jen/opt/miniconda3/lib/python3.9/site-packages/twarc/decorators2.py", line 104, in new_f
    resp = f(self, *args, **kwargs)
  File "/Users/Jen/opt/miniconda3/lib/python3.9/site-packages/twarc/decorators2.py", line 74, in new_f
    resp.raise_for_status()
  File "/Users/Jen/opt/miniconda3/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.twitter.com/2/tweets/search/recent?expansions=author_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id%2Centities.mentions.username%2Cattachments.poll_ids%2Cattachments.media_keys%2Cgeo.place_id&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Ctext%2Cpossibly_sensitive%2Creferenced_tweets%2Creply_settings%2Csource%2Cwithheld&media.fields=alt_text%2Cduration_ms%2Cheight%2Cmedia_key%2Cpreview_image_url%2Ctype%2Curl%2Cwidth%2Cpublic_metrics&poll.fields=duration_minutes%2Cend_datetime%2Cid%2Coptions%2Cvoting_status&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type&query=covid&max_results=1&start_time=2021-10-12T01%3A01%3A01%2B00%3A00&end_time=2021-10-13T01%3A01%3A01%2B00%3A00

**Comment by SamHames** [comment]
Oh, the other thing might be max_results, I don't think you can set it
below 10. Also that setting doesn't limit the number of tweets returned,
but the number of tweets in a single page of results. (we should probably
be checking that before we make the API call).

If you want to limit the number of tweets you're dealing with take a look
at
https://twarc-project.readthedocs.io/en/latest/api/library/#working-with-generators
