### ISSUE TITLE
Pass suspended/deleted accounts with infile for Timelines

### ISSUE THREAD

**Issue by icy-td** [DocNow/twarc#586]
I am running an analysis on an account with a volatile following and it is often the case that an account following it a few days ago can get suddenly be suspended or deleted. Right now, _ensure_user raises a specific fatal error if it comes across one such now-gone account in the infile list I'm using. Any advice about how to build a quick exception for these cases? Thank you! @SamHames

**Comment by igorbrigadir** [comment]
What's the exact error output from twarc.log?

**Comment by icy-td** [comment]
It's a raised error, **raise ValueError(f"No such user {user}"),  ValueError: No such user _cezve_m_**  As you can see, the [Twitter account](https://twitter.com/cezve_m) is gone. I get why to raise it intentionally, but it's a real issue for the kind of analysis I'm doing.


Traceback (most recent call last):
  File "C:\xxxxxxxxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\xxxxxxxxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\Scripts\twarc2.exe\__main__.py", line 7, in <module>
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\twarc\command2.py", line 1258, in timelines
    tweets = _timeline_tweets(
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\twarc\command2.py", line 1305, in _timeline_tweets
    tweets = T.timeline(
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\twarc\client2.py", line 894, in timeline
    user_id = self._ensure_user_id(user)
  File "C:\xxxxxxxxx\PycharmProjects\twarc2\venv\lib\site-packages\twarc\client2.py", line 1327, in _ensure_user_id
    raise ValueError(f"No such user {user}")
ValueError: No such user cezve_m

**Comment by SamHames** [comment]
Huh, I'd agree that's probably not very useful - @igorbrigadir, do you remember why we added that style of check at the client level? Was there something specific about the timeline endpoint?

@icy-td - can you share the full command you're running (I'm assuming this is the timelines command?). If you have academic access a workaround right now is to transform your infile into a set of searches using the `from:username` search syntax and use the [searches command](https://twarc-project.readthedocs.io/en/latest/twarc2_en_us/#searches).

If this is the timelines command my expectation would be that accounts that don't exist anymore don't have any tweets returned with a log message to note that, but don't otherwise stop the process.

**Comment by igorbrigadir** [comment]
I think `_ensure_user_id` was there to make sure user IDs from names could be fetched, and to disambiguate the edge case usernames that are all digits from user IDs.

And yeah, the timelines command shouldn't fail on missing users like that - so that's definitely a bug.

**Comment by SamHames** [comment]
Hmm, diving deeper - the timeline endpoint only takes user ids anyway. I don't think we should be accepting usernames for this functionality at all - the only reason this worked originally is because _ensure_user_id does an implicit lookup.

@icy-td - can you convert your input file to a list of user ids instead of usernames? I would recommend doing that anyway for your purposes, as changing account names is also a common avoidance tactic.

**Comment by icy-td** [comment]
Ah yes, there we go. Thanks, gents. Now it's time for me to sit back and let it scrape 700000+ timelines - wish me luck!

**Comment by SamHames** [comment]
Cool - I'm going to close this one then, but open a new one to look at how we might cleanup the documentation and stuff a bit.
