### ISSUE TITLE
UnboundLocalError: local variable 'extended_query' referenced before assignment

### ISSUE THREAD

**Issue by miguelwon** [DocNow/twarc#612]
Hi,
I'm getting this error:

```
Traceback (most recent call last):
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/bin/twarc2", line 8, in <module>
    sys.exit(twarc2())
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mwon_disk/disk2/paper_magalhaes_twitter/env/lib/python3.8/site-packages/twarc/command2.py", line 1663, in searches
    merged_query == extended_query or merged_query == f"({query})"
UnboundLocalError: local variable 'extended_query' referenced before assignment
```

I running `twarc v2.9.5` with subprocess and where `{handler}.txt`  is a list with tweets `conversation_id`s:

`twarc2 searches --no-context-annotations --combine-queries --archive convertation_files/{handler}.txt replies_jsons/replies_{handler}_cont.jsonl`

**Comment by igorbrigadir** [comment]
Can you provide the `convertation_files/{handler}.txt` file? How exactly are you running the command? is `{handler}` definitely getting replaced properly and isn't blank for example?

Also - is the input file just 1 line? If so, a quick workaround is to not specify `--combine-queries` - there definitely seems to be a bug when you specify an input file with just 1 line and also specify `--combine-queries`

**Comment by SamHames** [comment]
Yeah this looks like a bug, I'll see if I can recreate locally.

**Comment by SamHames** [comment]
I think I have a fix for the underlying issue as well, just didn't have a chance to properly test it today.
